# -*- coding: utf-8 -*-
"""Ambil Data Penjualan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10mqQsjDmagvk09U8hM5a2cXGe405PXYD
"""

import pandas as pd

# Load data
file_path = 'TRANSAKSI HARIAN MI STORE 2026.xlsx'
df = pd.read_excel(file_path, header=None)

# Ambil header
header = df.iloc[2]

# Ambil data
data = df.iloc[3:].copy()
data.columns = header

# Pilih kolom
clean_df = data[['NO.NOTA', 'QTY', 'BARANG', 'SRP']]

# Rename
clean_df.columns = ['No_Nota', 'Qty', 'Barang', 'Harga']

# Bersihkan data kosong
clean_df = clean_df.dropna(subset=['No_Nota'])

# Reset index
clean_df = clean_df.reset_index(drop=True)

# 🔍 Tampilkan seluruh data
print(clean_df)

# 💾 Simpan ke Excel
output_path = 'clean_transaksi_mi_store.xlsx'
clean_df.to_excel(output_path, index=False)

print(f"\nFile berhasil disimpan di: {output_path}")

import pandas as pd

# 1. Konfigurasi File
file_path = 'TRANSAKSI HARIAN MI STORE 2026.xlsx'
daftar_sheet = ['JAN26', 'FEB26', 'MAR26']
output_path = 'clean_transaksi_mi_store_gabungan.xlsx'

# List untuk menampung data dari setiap sheet yang sudah bersih
all_cleaned_data = []

print("Memulai proses pembersihan data...")

# 2. Perulangan untuk memproses setiap sheet
for sheet in daftar_sheet:
    try:
        # Membaca data dari sheet tertentu
        df = pd.read_excel(file_path, sheet_name=sheet, header=None)

        # --- PROSES PEMBERSIHAN DATA (Logika dari koding sebelumnya) ---
        # Ambil header dari baris ke-3 (indeks 2)
        header = df.iloc[2]

        # Ambil data dari baris ke-4 ke bawah
        data = df.iloc[3:].copy()
        data.columns = header

        # Pilih kolom yang diperlukan
        clean_df = data[['NO.NOTA', 'QTY', 'BARANG', 'SRP']].copy()

        # Rename kolom agar seragam
        clean_df.columns = ['No_Nota', 'Qty', 'Barang', 'Harga']

        # Bersihkan data kosong pada kolom No_Nota
        clean_df = clean_df.dropna(subset=['No_Nota'])

        # Tambahkan kolom keterangan 'Bulan' agar kita tahu asal datanya
        clean_df['Bulan'] = sheet

        # Masukkan ke dalam list
        all_cleaned_data.append(clean_df)
        print(f"✅ Sheet {sheet} berhasil diproses.")

    except Exception as e:
        print(f"❌ Gagal memproses sheet {sheet}: {e}")

# 3. Penggabungan Data
if all_cleaned_data:
    # Menggabungkan semua DataFrame yang ada di list menjadi satu
    df_final = pd.concat(all_cleaned_data, ignore_index=True)

    # Menampilkan ringkasan data
    print("\n--- Ringkasan Data Gabungan ---")
    print(df_final.head())
    print(f"\nTotal baris terkumpul: {len(df_final)}")

    # 4. Simpan ke Excel Baru
    df_final.to_excel(output_path, index=False)
    print(f"\nFile gabungan berhasil disimpan di: {output_path}")
else:
    print("Tidak ada data yang berhasil diproses.")

import pandas as pd

# 1. Konfigurasi
file_path = 'TRANSAKSI HARIAN MI STORE 2026 - Copy.xlsx'
output_path = 'REKAP_PENJUALAN_LENGKAP_2026.xlsx'

# List nama sheet sesuai file kamu
daftar_sheet = ['JAN26', 'FEB26', 'MAR26', 'APR26', 'MEI26', 'JUN26',
                'JUL26', 'AGS26', 'SEP26', 'OKT26', 'NOV26', 'DES26']

all_cleaned_data = []

print("🚀 Sedang menyatukan data transaksi setahun...")

for sheet in daftar_sheet:
    try:
        # Baca sheet tanpa header karena struktur tabel berulang (banyak header di tengah)
        df = pd.read_excel(file_path, sheet_name=sheet, header=None)

        current_date = None
        sheet_rows = []

        for i, row in df.iterrows():
            # Kolom A (index 0) biasanya berisi Tanggal atau nomor urut
            val_a = str(row[0]).strip().upper()

            # A. Deteksi Baris Tanggal (Ciri: mengandung '/' atau nama hari)
            if '/' in val_a or 'SENIN' in val_a or 'SELASA' in val_a or 'RABU' in val_a or \
               'KAMIS' in val_a or 'JUMAT' in val_a or 'SABTU' in val_a or 'MINGGU' in val_a:
                current_date = val_a
                continue

            # B. Ambil data jika kolom NO.NOTA (index 2) berisi angka
            no_nota = str(row[2]).strip()
            if no_nota.isdigit():
                sheet_rows.append({
                    'Tanggal': current_date,
                    'Bulan': sheet,
                    'No_Nota': no_nota,
                    'Qty': row[3],
                    'Barang': row[4],
                    'Harga_SRP': row[6],
                    'Keterangan': row[7],
                    'Harga_Jadi': row[8],
                    'EDC': row[9],    # Kolom EDC
                    'Kredit': row[10]  # Kolom Kredit
                })

        if sheet_rows:
            all_cleaned_data.append(pd.DataFrame(sheet_rows))
            print(f"✅ Sheet {sheet} selesai.")

    except Exception as e:
        print(f"⚠️ Sheet {sheet} dilewati: {e}")

# 2. Penggabungan dan Pembersihan Akhir
if all_cleaned_data:
    df_final = pd.concat(all_cleaned_data, ignore_index=True)

    # Merapikan kolom Tanggal (mengambil bagian tanggal saja, membuang nama hari)
    # Contoh: "01/01/2025 RABU" -> "01/01/2025"
    df_final['Tanggal'] = df_final['Tanggal'].str.extract(r'(\d{1,2}/\d{1,2}/\d{4}|\d{4}-\d{2}-\d{2})')

    # Mengisi kolom EDC dan Kredit yang kosong (NaN) dengan 0 agar bisa dijumlahkan
    df_final['EDC'] = df_final['EDC'].fillna(0)
    df_final['Kredit'] = df_final['Kredit'].fillna(0)

    # Simpan ke Excel
    df_final.to_excel(output_path, index=False)
    print(f"\n✨ BERHASIL!")
    print(f"Data tersimpan di: {output_path}")
    print(f"Total Transaksi: {len(df_final)} baris")
else:
    print("❌ Tidak ada data yang ditemukan.")